### PR TITLE
Onboarding Screens

### PR DESCRIPTION
**Pull request by tydahlwave**
Onboarding Flow:
1. Welcome
2. Terms of Service
3. Choose Campus

Also Added/Changed:
- Terms of Service cell on profile screen
- Push transition for notifications screen (rather than modal)
- Dynamic font so anyone can read the Terms of Service
- No longer present login screen on app launch

I also tested these screens on each device to make sure it fits.
Would appreciate feedback on UI and code.

screen shot 2018-09-24 at 9 40 54 pm
screen shot 2018-09-24 at 9 40 58 pm
screen shot 2018-09-24 at 9 41 02 pm
screen shot 2018-09-24 at 9 41 11 pm
screen shot 2018-09-24 at 9 41 23 pm
screen shot 2018-09-24 at 9 58 33 pm

### CODE REVIEW

**Comment by landongerrits** [comment]
nice, thanks for doing this!

I think the flow makes sense but the buttons and text could look better

I personally am not a fan of the photo background. I think having just a white or some other color-blocked background would be better.

Where are you getting that intro mission statement from?

Other small things: 

- [ ] - I think the on boarding TOC text could be full screen similar to your last screenshot (maybe try a light grey or blue background and dark grey text?)

- [ ] - Settings should have a cell showing your listed campus

**Comment by cbatch** [comment]
I listed a lot of my thoughts already in the slack channel, but random other thoughts:
- more padding above the icon for the settings/profile view
- go with the white background and then make any button that you have the `appTint` color
- if it's not required by some legal thing, don't have the extra alert when agreeing to the terms
- break out the campus into it's own section, show each campus as a row with the selection style `.none` and as the last row in that list have "Choose Campus" which would take you into that view to select and manage them

**Comment by tydahlwave** [comment]
Updated the onboarding screens.

Also added some restrictions:
- Cannot advance on TOS or Privacy Policy screens without pressing "Agree", but can go back to previous screens
- Cannot go back to previous screens once the user is on the "Choose Campus" screen

screen shot 2018-09-28 at 11 27 01 pm
screen shot 2018-09-28 at 11 27 07 pm
screen shot 2018-09-28 at 11 27 17 pm
screen shot 2018-09-28 at 11 27 20 pm

**Comment by landongerrits** [comment]
First screen looks good, the "swipe to begin" is nice (unobtrusive too)

the agree buttons for the TOC and PrivacyPolicy could probably match the buttons of the events/community groups/missions buttons. 

The paging dots with a button on 2nd and 3rd pages looks a little odd. Is there some visual indication that the user has agreed to either document? Will tapping agree push you to the next page? IDK having conditional items on a page control still seems a little off to me

 I think I may have to see this working on app to get a better perspective on this

**Comment by landongerrits** [comment]
I think the campus selection screen needs to fit the form of the previous 3 screens (needs to have page dots)

Potential solution for now: only do page dots for the first 3 pages and then when user agrees to both documents "push" on the campus selection

Ideally, I would like to see campus selection as forth screen with page dots visible. I imagine that screen as a collection view with the campuses as selectable tiles. (maybe for an improvement for 2.1)

**Review by landongerrits — APPROVED** [review]
approved for merge, but I think we should continue our conversation on the UX of the paging control

**Pull request merged**
