### PR TITLE
Login Button UI

### PR DESCRIPTION
**Pull request by tydahlwave**
Changed the color, font, and logos for the Facebook and Google login buttons.
They should be following the recommended standards set by Facebook and Google now.
Also updated the Facebook button on the Events detail page.

OLD and NEW designs:
screen shot 2018-09-29 at 8 21 53 pmscreen shot 2018-09-29 at 8 17 22 pm
screen shot 2018-09-29 at 8 20 53 pm

### CODE REVIEW

**Comment by landongerrits** [comment]
I think center the "sign in with google text" between the google icon and the right side of the button

I think keep both buttons a solid color (can be different colors) 

OR 

both buttons have no back ground button and it's just the icon and text

**Comment by tydahlwave** [comment]
Here is an alternate version of the Facebook button:
screen shot 2018-09-29 at 9 16 29 pm

**Comment by landongerrits** [comment]
looks good, approved for merge


Cam is working on his PR for changing the app tint color which will affect the login button color, and the login subtext

**Review by landongerrits — APPROVED** [review]
approved for merge to release 2.0

**Pull request merged**
